<?php

namespace App\Services;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use ZipArchive;

class BackupService
{
    private string $backupDir;

    public function __construct()
    {
        $this->backupDir = storage_path('app/backups');
        if (! File::exists($this->backupDir)) {
            File::makeDirectory($this->backupDir, 0755, true);
        }
    }

    public function createBackup(): string
    {
        set_time_limit(300);

        $timestamp = now()->format('Y-m-d_H-i-s');
        $filename = "backup_{$timestamp}.zip";
        $zipPath = $this->backupDir . DIRECTORY_SEPARATOR . $filename;

        $zip = new ZipArchive;
        if ($zip->open($zipPath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
            throw new \RuntimeException("Cannot create ZIP at: {$zipPath}");
        }

        // 1. Database dump
        $sql = $this->dumpDatabase();
        $zip->addFromString('database.sql', $sql);

        // 2. Storage files
        $this->addStorageToZip($zip);

        // 3. Metadata
        $meta = json_encode([
            'version'    => '1.0',
            'created_at' => now()->toIso8601String(),
            'app_name'   => config('app.name'),
            'app_url'    => config('app.url'),
            'laravel'    => app()->version(),
            'php'        => PHP_VERSION,
        ], JSON_PRETTY_PRINT);
        $zip->addFromString('backup_meta.json', $meta);

        $zip->close();

        return $filename;
    }

    public function restoreFromZip(string $zipPath): void
    {
        set_time_limit(600);

        $zip = new ZipArchive;
        if ($zip->open($zipPath) !== true) {
            throw new \RuntimeException('Cannot open ZIP file.');
        }

        $extractDir = storage_path('app/restore_tmp_' . time());
        $zip->extractTo($extractDir);
        $zip->close();

        try {
            // 1. Restore database
            $sqlFile = $extractDir . '/database.sql';
            if (! file_exists($sqlFile)) {
                throw new \RuntimeException('database.sql not found in ZIP.');
            }
            $this->importDatabase(file_get_contents($sqlFile));

            // 2. Restore storage files
            $storageSrc = $extractDir . '/storage';
            if (File::exists($storageSrc)) {
                $storageDest = storage_path('app/public');
                if (File::exists($storageDest)) {
                    $this->removeDirectory($storageDest);
                }
                File::copyDirectory($storageSrc, $storageDest);
            }

            // Refresh DB connection pool
            DB::reconnect();
        } finally {
            $this->removeDirectory($extractDir);
        }
    }

    public function listBackups(): array
    {
        $files = File::glob($this->backupDir . DIRECTORY_SEPARATOR . '*.zip');
        $backups = [];

        foreach ($files as $path) {
            $name = basename($path);
            $size = filesize($path);
            $backups[] = [
                'filename' => $name,
                'size'     => $this->formatBytes($size),
                'size_raw' => $size,
                'created'  => \Carbon\Carbon::createFromTimestamp(filemtime($path))->format('d/m/Y H:i:s'),
            ];
        }

        usort($backups, fn ($a, $b) => $b['size_raw'] <=> $a['size_raw']);

        return $backups;
    }

    public function getBackupPath(string $filename): string
    {
        $filename = basename($filename); // prevent path traversal
        return $this->backupDir . DIRECTORY_SEPARATOR . $filename;
    }

    public function deleteBackup(string $filename): void
    {
        $path = $this->getBackupPath($filename);
        if (File::exists($path)) {
            File::delete($path);
        }
    }

    private function dumpDatabase(): string
    {
        $config = config('database.connections.' . config('database.default'));
        $db = $config['database'];

        $lines = [];
        $lines[] = '-- Backup generated by ' . config('app.name');
        $lines[] = '-- Date: ' . now()->toIso8601String();
        $lines[] = '';
        $lines[] = 'SET FOREIGN_KEY_CHECKS=0;';
        $lines[] = 'SET NAMES utf8mb4;';
        $lines[] = "USE `{$db}`;";
        $lines[] = '';

        $tables = DB::select('SHOW TABLES');
        $tableKey = 'Tables_in_' . $db;

        foreach ($tables as $tableRow) {
            $table = $tableRow->$tableKey;

            // DROP + CREATE
            $createResult = DB::select("SHOW CREATE TABLE `{$table}`");
            $createSql = $createResult[0]->{'Create Table'};
            $lines[] = "DROP TABLE IF EXISTS `{$table}`;";
            $lines[] = $createSql . ';';
            $lines[] = '';

            // Rows
            $rows = DB::table($table)->get();
            if ($rows->isEmpty()) {
                continue;
            }

            $columns = array_keys((array) $rows->first());
            $colList = implode(', ', array_map(fn ($c) => "`{$c}`", $columns));

            foreach ($rows as $row) {
                $values = array_map(function ($val) {
                    if ($val === null) return 'NULL';
                    return "'" . addslashes((string) $val) . "'";
                }, (array) $row);

                $lines[] = "INSERT INTO `{$table}` ({$colList}) VALUES (" . implode(', ', $values) . ');';
            }
            $lines[] = '';
        }

        $lines[] = 'SET FOREIGN_KEY_CHECKS=1;';

        return implode("\n", $lines);
    }

    private function importDatabase(string $sql): void
    {
        $config = config('database.connections.' . config('database.default'));

        $mysqli = new \mysqli(
            $config['host'],
            $config['username'],
            $config['password'],
            $config['database'],
            (int) ($config['port'] ?? 3306)
        );

        if ($mysqli->connect_errno) {
            throw new \RuntimeException('MySQLi connect failed: ' . $mysqli->connect_error);
        }

        $mysqli->set_charset('utf8mb4');

        if (! $mysqli->multi_query($sql)) {
            throw new \RuntimeException('MySQLi multi_query failed: ' . $mysqli->error);
        }

        // Flush all result sets to prevent "Commands out of sync"
        do {
            if ($result = $mysqli->store_result()) {
                $result->free();
            }
        } while ($mysqli->more_results() && $mysqli->next_result());

        $mysqli->close();
    }

    private function addStorageToZip(ZipArchive $zip): void
    {
        $sourceDir = storage_path('app/public');
        if (! File::exists($sourceDir)) {
            return;
        }

        $files = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($sourceDir, \RecursiveDirectoryIterator::SKIP_DOTS),
            \RecursiveIteratorIterator::SELF_FIRST
        );

        foreach ($files as $file) {
            $relativePath = 'storage' . DIRECTORY_SEPARATOR . substr($file->getRealPath(), strlen($sourceDir) + 1);
            $relativePath = str_replace('\\', '/', $relativePath);

            if ($file->isDir()) {
                $zip->addEmptyDir($relativePath);
            } else {
                $zip->addFile($file->getRealPath(), $relativePath);
            }
        }
    }

    private function removeDirectory(string $path): void
    {
        if (File::exists($path)) {
            File::deleteDirectory($path);
        }
    }

    private function formatBytes(int $bytes): string
    {
        if ($bytes >= 1073741824) return round($bytes / 1073741824, 2) . ' GB';
        if ($bytes >= 1048576) return round($bytes / 1048576, 2) . ' MB';
        if ($bytes >= 1024) return round($bytes / 1024, 2) . ' KB';
        return $bytes . ' B';
    }
}
